import Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.

hostname =
  cond do
    app_name = System.get_env("APP_NAME") -> "#{app_name}.gigalixirapp.com"
    true -> "buckitup.app"
  end

config :chat, ChatWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json",
  # Possibly not needed, but doesn't hurt
  http: [port: {:system, "PORT"}],
  url: [host: hostname, port: 443],
  secret_key_base:
    Map.get(
      System.get_env(),
      "SECRET_KEY_BASE",
      "BKyA6n6KrL/mmKlyg5a+4/ZlWq0cN3dFqfvNj9zaw6Acvnp++u6bXN5rkns5xVpE"
    ),
  check_origin: [
    "https://offline-chat.gigalixirapp.com",
    "https://buckitup.app"
  ],
  allow_reset_data: false

# url: [host: "buckitup.app", port: 443],
# secret_key_base: Map.fetch!(System.get_env(), "SECRET_KEY_BASE"),
# check_origin: ["https://buckitup.app"],
# server: true,
# https: [
#  port: 443,
#  cipher_suite: :strong,
#  cacertfile: "priv/cert/buckitup_app.ca-bundle",
#  certfile: "priv/cert/buckitup_app.crt",
#  keyfile: "priv/cert/priv.key"
# ],
# force_ssl: [hsts: true]

# Do not print debug messages in production
config :logger, level: :info

# ## SSL Support
#
# To get SSL working, you will need to add the `https` key
# to the previous section and set your `:url` port to 443:
#
#     config :chat, ChatWeb.Endpoint,
#       ...,
#       url: [host: "example.com", port: 443],
#       https: [
#         ...,
#         port: 443,
#         cipher_suite: :strong,
#         keyfile: System.get_env("SOME_APP_SSL_KEY_PATH"),
#         certfile: System.get_env("SOME_APP_SSL_CERT_PATH")
#       ]
#
# The `cipher_suite` is set to `:strong` to support only the
# latest and more secure SSL ciphers. This means old browsers
# and clients may not be supported. You can set it to
# `:compatible` for wider support.
#
# `:keyfile` and `:certfile` expect an absolute path to the key
# and cert in disk or a relative path inside priv, for example
# "priv/ssl/server.key". For all supported SSL configuration
# options, see https://hexdocs.pm/plug/Plug.SSL.html#configure/1
#
# We also recommend setting `force_ssl` in your endpoint, ensuring
# no data is ever sent via http, always redirecting to https:
#
#     config :chat, ChatWeb.Endpoint,
#       force_ssl: [hsts: true]
#
# Check `Plug.SSL` for all available options in `force_ssl`.
